### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by markholland** [chiragramani/FlipperReleases#7]
Build is failing due to merge conflicts when performing the cherry picks.

```
Auto-merging desktop/scripts/build-release.tsx
CONFLICT (content): Merge conflict in desktop/scripts/build-release.tsx
Auto-merging iOS/FlipperKit.xcodeproj/project.pbxproj
CONFLICT (content): Merge conflict in iOS/FlipperKit.xcodeproj/project.pbxproj
Auto-merging iOS/Podfile
Auto-merging iOS/Podfile.lock
CONFLICT (content): Merge conflict in iOS/Podfile.lock
error: could not apply 6cc083b86... Update to enable universal builds of Flipper
```

**Comment by phucprime** [comment]
any update?

**Comment by olcayertas** [comment]
I have forked the repo and fixed the build problems. It still fails at the code sign step but generates the app:

https://github.com/olcayertas/FlipperAppleSlicon

**Comment by umangloria** [comment]
> I have forked the repo and fixed the build problems. It still fails at the code sign step but generates the app:
> 
> https://github.com/olcayertas/FlipperAppleSlicon

I tried tried from your release section but it says it is corrupted. Then I tried to generate it locally on my machine and I am getting this error:
```
AbortError failed with type: aborted; message: The user aborted a request.
Retrying in 123 milliseconds, attempt 1 error: AbortError, The user aborted a request.
Failed to build flipper-server FetchError: network timeout at https://facebook.com/images/assets_DO_NOT_HARDCODE/facebook_icons/box_outline_48.png
    at wrappedFetch (/Users/umangloriya/Documents/flipper/flipper/desktop/node_modules/@adobe/node-fetch-retry/index.js:230:43)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  type: 'request-timeout'
} FetchError: network timeout at https://facebook.com/images/assets_DO_NOT_HARDCODE/facebook_icons/box_outline_48.png
    at wrappedFetch (/Users/umangloriya/Documents/flipper/flipper/desktop/node_modules/@adobe/node-fetch-retry/index.js:230:43)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by olcayertas** [comment]
@umangloria I will check it.
